 ### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe with kafka 7",
  "email": "test_kafka_event7@example.com",
  "address": "123 main street26, Springfield",
  "dateOfBirth": "1995-09-14",
  "registeredDate": "2024-11-14"
}

###